### ISSUE TITLE
Recursion structs

### ISSUE THREAD

**Issue by sah4ez** [swipe-io/swipe#3]
**Describe the bug**
Recursion generation

**To Reproduce**
1. Return from the method this struct 
```
type Node struct {
    Child []*Node
}
```
2. run `swipe gen ./path/to/transport.go
3. stuuuck...

**Expected behavior**
Generated code for recursion struct.

**Screenshots**
no

**Swipe Version:**
v1.26.7

**Additional context**
no

**Comment by l-vitaly** [comment]
Fixed!
