### ISSUE TITLE
Excessive underscores in generated env var name when using numbers in fields

### ISSUE THREAD

**Issue by r3nat** [swipe-io/swipe#6]
**Describe the bug**
See title

**To Reproduce**
1. Create config.go
```
package testconfig

type Config struct {
	FieldName123 string `env:""`
}
```
2. Use `ConfigEnv` to build
3. There is `FIELD_NAME_123` in config_gen.go

**Expected behavior**
I'm expecting to see `FIELD_NAME123` in generated config

**Swipe Version:**
v1.26.7

**Comment by l-vitaly** [comment]
fixed
